"""
Generate water_v2/water_albedo.png (tileable RGBA) and rewrite water_full.obj / water_top.obj
with 0..1 UVs so the texture is not stuck in a terrain atlas strip.

Run from project root:
  python blocky_game/blocks/gen_water_albedo.py
"""
from __future__ import annotations

import math
import os

from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_TEX = os.path.join(ROOT, "water_v2", "water_albedo.png")
OUT_FULL = os.path.join(ROOT, "water_v2", "water_full.obj")
OUT_TOP = os.path.join(ROOT, "water_v2", "water_top.obj")

TEX_SIZE = 128


def make_water_albedo(size: int) -> Image.Image:
    """Toroidal tile: only 2pi-periodic terms so opposite edges match (triplanar repeats cleanly)."""
    img = Image.new("RGBA", (size, size))
    px = img.load()
    tp = math.tau
    for j in range(size):
        fy = (j + 0.5) / size
        for i in range(size):
            fx = (i + 0.5) / size
            w1 = math.sin(tp * (3.0 * fx + 1.2 * fy))
            w2 = math.sin(tp * (4.0 * fy - 2.0 * fx))
            w3 = math.sin(tp * (2.0 * (fx + fy)))
            w4 = math.sin(tp * 7.0 * fx) * math.sin(tp * 6.0 * fy)
            wave = 0.34 * w1 + 0.28 * w2 + 0.22 * w3 + 0.16 * w4
            wave = wave * 0.5 + 0.5

            r = min(255, int(42 + 58 * wave))
            g = min(255, int(108 + 92 * wave))
            b = min(255, int(178 + 72 * wave))

            aw = math.sin(tp * (2.0 * fx + 3.0 * fy)) * 0.5 + 0.5
            a = int(168 + 48 * aw)
            a = max(148, min(228, a))
            px[i, j] = (r, g, b, a)
    return img


def _fmt_v(v: tuple[float, float, float]) -> str:
    return f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}"


def _write_obj(
    path: str,
    name: str,
    verts: list[tuple[float, float, float]],
    faces: list[tuple[list[int], int]],
) -> None:
    """
    verts: 1-based order in faces
    faces: ( [i1,i2,i3,i4], vn_index )  quad per face, normal index 1-based
    """
    lines = [
        "# Generated by gen_water_albedo.py — UVs 0..1 per face for water_albedo.png",
        f"o {name}",
    ]
    for v in verts:
        lines.append(_fmt_v(v))
    lines.append("")
    # 4 UVs per face: (0,0)(1,0)(1,1)(0,1) assigned in vertex order per face
    vt_lines: list[str] = []
    f_lines: list[str] = []
    vt_i = 0
    for quad, vni in faces:
        uvs = [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
        t_start = vt_i + 1
        for u, vv in uvs:
            vt_i += 1
            vt_lines.append(f"vt {u:.6f} {vv:.6f}")
        parts = [f"{quad[k]}/{t_start + k}/{vni}" for k in range(4)]
        f_lines.append("f " + " ".join(parts))
    lines.append("vn 0.000000 1.000000 0.000000")
    lines.append("vn -1.000000 0.000000 0.000000")
    lines.append("vn 0.000000 0.000000 -1.000000")
    lines.append("vn 0.000000 -1.000000 0.000000")
    lines.append("vn 0.000000 0.000000 1.000000")
    lines.append("vn 1.000000 0.000000 0.000000")
    lines.extend(vt_lines)
    lines.append("s off")
    lines.extend(f_lines)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def main() -> None:
    tex = make_water_albedo(TEX_SIZE)
    tex.save(OUT_TEX, "PNG")
    print("Wrote", OUT_TEX)

    # water_full: same topology as shipped cube (8 verts, 6 quads)
    verts_full = [
        (1.0, 1.0, 1.0),
        (1.0, 0.0, 1.0),
        (0.0, 1.0, 1.0),
        (0.0, 0.0, 1.0),
        (1.0, 1.0, 0.0),
        (1.0, 0.0, 0.0),
        (0.0, 1.0, 0.0),
        (0.0, 0.0, 0.0),
    ]
    faces_full = [
        ([1, 5, 7, 3], 1),
        ([4, 3, 7, 8], 2),
        ([8, 7, 5, 6], 3),
        ([6, 2, 4, 8], 4),
        ([2, 1, 3, 4], 5),
        ([6, 5, 1, 2], 6),
    ]
    _write_obj(OUT_FULL, "water_full", verts_full, faces_full)
    print("Wrote", OUT_FULL)

    y_top = 0.875
    verts_top = [
        (1.0, y_top, 1.0),
        (1.0, 0.0, 1.0),
        (0.0, y_top, 1.0),
        (0.0, 0.0, 1.0),
        (1.0, y_top, 0.0),
        (1.0, 0.0, 0.0),
        (0.0, y_top, 0.0),
        (0.0, 0.0, 0.0),
    ]
    faces_top = [
        ([1, 5, 7, 3], 1),
        ([4, 3, 7, 8], 2),
        ([8, 7, 5, 6], 3),
        ([6, 2, 4, 8], 4),
        ([2, 1, 3, 4], 5),
        ([6, 5, 1, 2], 6),
    ]
    _write_obj(OUT_TOP, "water_top", verts_top, faces_top)
    print("Wrote", OUT_TOP)


if __name__ == "__main__":
    main()
